### ISSUE TITLE
Question: how to share or repost other's activity? 

### ISSUE THREAD

**Issue by junghyungu** [GetStream/stream-js#271] opened 2019-12-19 02:03 UTC

**Comment by jaapbakker88** [comment] 2020-03-02 16:13
Hi @junghyungu, sorry for the late reply:

You can use reactions for this: just add a reaction with a title repost and use targetFeeds to send the activity to the other users feed.  

```
const comment = await client.reactions.add(
    'repost', 
    activity, 
    {}, 
    { targetFeeds: [`${feedGroup}:${userId}`]} 
);
```

**Comment by ferhatelmas** [comment] 2020-04-06 15:29
@junghyungu closing, if you still see an issue, please let us know.

**Closed by ferhatelmas** 2020-04-06 15:29 UTC
Labels: question

**Comment by fedealconada** [comment] 2021-05-01 02:02
If I have added a reaction to some activity and then I want to display the feed (including reactions), ordered by recent "actions" (action would be a new activity added, a new reaction, etc) like:

FEED
------
ACTIVITY 4 --> date: 30/04
REACTION TO ACTIVITY 1 30/04
ACTIVITY 3 29/04
ACTIVITY 2 28/04
ACTIVITY 1 27/04

how can I do this? I can't find out the way of doing this... 
`client.feed('timeline', 'bob').get({ 
    reactions: { own: true, recent: true, counts: true } 
});
`
that will not work to my use case... and this is why: considering the example above, if I were to call this:
`
client.get({  
  limit:3, enrich:true, 
  reactions: {own: true, counts: true, recent: true}, 
}) 
`
it will return the last 3 activities: ACTIVITY 4, ACTIVITY 3, and ACTIVITY 2 but ACTIVITY 1 will not be returned. The problem is that a REACTION TO ACTIVITY 1 happened recently, but as my limit is 3 it's not retrieving this activity.

I'm not sure if I'm explaining my problem well (I hope so).  My idea is to be able to show, on my app, a feed like in the example but I'm not being able to retrieve the reaction that happened recently of an "old activity".

Thoughts @ferhatelmas ?
