### ISSUE TITLE
reading follow stats always return 403

### ISSUE THREAD

**Issue by willdd56** [GetStream/stream-js#407] opened 2021-01-05 08:19 UTC
I call followStats() on backend site to get user's follow stats. But it always return status code 403 with message: "You do not have permission to perform this action."

gz#8395

**Comment by shodgetts** [comment] 2021-01-05 08:24
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/8395'>Zendesk ticket #8395</a>:<br><br>This request was closed and merged into request #8393 "Docs feedback on Follows > Follo...".

**Comment by willdd56** [comment] 2021-01-05 08:50
> Agent comment from Séni Gueye in [Zendesk ticket #8395](https://getstream.zendesk.com/agent/tickets/8395):
> 
> This request was closed and merged into request #8393 "Docs feedback on Follows > Follo...".

Thank you for replying. Can I have the link of #8393 ?

**Comment by ferhatelmas** [comment] 2021-01-15 11:17
@willdd56 client side needs adding permissions into your app, please give your app/feed group details via https://getstream.io/support or here, and I will add.

Since it's not a bug related to SDK, will close this ticket.

**Closed by ferhatelmas** 2021-01-15 11:17 UTC
