### ISSUE TITLE
Received Error: secretOrPrivateKey must have a value when Instantiate a new client from client side

### ISSUE THREAD

**Issue by timothywangdev** [GetStream/stream-js#178] opened 2018-07-02 00:38 UTC
- getstream: v3.18.0
- node: v8.11.2 

```js
client = stream.connect('ju3pey94bxm5', null, '38296');
```

output
```
/root/projects/test/node_modules/jsonwebtoken/sign.js:97
    throw err;
    ^

Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/root/projects/test/node_modules/jsonwebtoken/sign.js:101:20)
    at Object.exports.JWTScopeToken (/root/projects/test/node_modules/getstream/src/lib/signing.js:114:19)
    at StreamClient.initialize (/root/projects/test/node_modules/getstream/src/lib/client.js:95:43)
    at new StreamClient (/root/projects/test/node_modules/getstream/src/lib/client.js:26:19)
    at Object.connect (/root/projects/test/node_modules/getstream/src/getstream.js:45:10)
    at Object.<anonymous> (/root/projects/test/test.js:3:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by tbarbugli** [comment] 2018-07-02 07:45
this is indeed a regression introduced by: https://github.com/GetStream/stream-js/commit/1fba92589970aee96d4fe6559d0fd2e92994fc16 @dwightgunning we should not perform any signing client-side (eg. browser) @timothywangdev we'll push a fix for this asap (most likely today). In the meantime you can use `3.17.0`

**Comment by tbarbugli** [comment] 2018-07-02 07:53
jumped to conclusion too early; that code is not executed when running on the browser. @timothywangdev are you running this code server-side?

**Comment by dwightgunning** [comment] 2018-07-02 08:12
Hi @timothywangdev - just to be sure, can you confirm you're seeing the error raised when calling `stream.connect()` from within a Node.js (8.11.2) application?

I ask because the line of code raising the error is within a conditional block that should only execute on non-browser / trusted environments (e.g. backend services). I'd like to check our browser detection is working properly.

The error is being raised as an API Secret isn't included with your call to `connect(api_key, api_secret, app_id)`. That 'api_secret' parameter must be `null` in browser / untrusted environments (where the secret should not be exposed) but is typically passed in backend app. However I believe it is valid to have a backend service that doesn't want write access and therefore shouldn't require the 'secret'. This seems to be the bug you've identified.

**Comment by timothywangdev** [comment] 2018-07-02 18:24
@dwightgunning the entire script is ran in a nodejs env by calling 
```
node test.js
```

**Comment by dwightgunning** [comment] 2018-07-03 10:17
Thanks for the additional details.

Will look at how we should handle this case and how we can hopefully give a more intuitive error.

**Comment by dwightgunning** [comment] 2018-07-06 08:28
@timothywangdev I've raised a PR that should resolve this.

Essentially you shouldn't see an exception when calling `connect()` without a 'secret'. Though a secret is required when calling functions that involve 'signing' and JWTs (and this is where errors will be raised if no 'secret' is present).

**Closed** 2018-07-30 08:34 UTC
